#! /bin/bash

function run_action() {
  if [ "$1" = "start" ]; then
    docker compose -p bng-$2 -f $2/docker-compose.yaml up -d
  else
    docker compose -p bng-$2 -f $2/docker-compose.yaml down
  fi
}

if [ "$1" = "start" ]; then
  docker network ls | grep bng > /dev/null || docker network create bng
  docker compose -p bng-gateway -f gateway/docker-compose.yaml up -d

  if [ "$2" = "all" ]; then
    run_action "start" "app"
    run_action "start" "api-auth"
    run_action "start" "api-events"
    run_action "start" "api-exams"
    run_action "start" "api-gears"
    exit 1
  fi

elif [ "$1" = "stop" ]; then
  if [ "$2" = "all" ]; then
    run_action "stop" "app"
    run_action "stop" "api-auth"
    run_action "stop" "api-events"
    run_action "stop" "api-exams"
    run_action "stop" "api-gears"

    docker compose -p bng-gateway -f gateway/docker-compose.yaml down
    docker network rm -f bng
    exit 1
  fi
else
  echo "Usage: $0 start|stop service_1 [service_2 ...]"
  exit 1
fi

for word in "$@"; do
  case $word in
    "app")
      run_action "$1" "app"
      ;;
    "auth")
      run_action "$1" "api-auth"
      ;;
    "events")
      run_action "$1" "api-events"
      ;;
    "exams")
      run_action "$1" "api-exams"
      ;;
    "gears")
      run_action "$1" "api-gears"
      ;;
    *)
      continue
      ;;
  esac
done
